version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nerutalk_db
      POSTGRES_USER: nerutalk_user
      POSTGRES_PASSWORD: nerutalk_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://nerutalk_user:nerutalk_password@db:5432/nerutalk_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    volumes:
      - .:/app
    command: python main.py

volumes:
  postgres_data:
